CREATE DATABASE trtemplate ENCODING='UTF-8' LC_COLLATE = 'tr_TR.UTF-8' LC_CTYPE='tr_TR.UTF-8' TEMPLATE template0;
    CREATE DATABASE "dwh-airflow" TEMPLATE trtemplate ;
    CREATE ROLE "dwh-airflow" NOLOGIN;
    CREATE ROLE "dwh-airflow_owner" password '1aA23.279.!' IN ROLE "dwh-airflow";
    CREATE ROLE "dwh-airflow_app" NOLOGIN IN ROLE "dwh-airflow";
    CREATE ROLE "dwh-airflow_readonly" NOLOGIN IN ROLE "dwh-airflow";
    CREATE ROLE "dwh-airflow_dwh" NOLOGIN IN ROLE "dwh-airflow";
    CREATE ROLE "dwh-airflow_developer" NOLOGIN IN ROLE "dwh-airflow";
    CREATE ROLE "dwh-airflow_report" NOLOGIN IN ROLE "dwh-airflow";
    \c "dwh-airflow";

GRANT CONNECT, TEMP ON DATABASE "dwh-airflow" TO "dwh-airflow";
GRANT USAGE ON SCHEMA public TO "dwh-airflow";
ALTER DEFAULT PRIVILEGES FOR ROLE "dwh-airflow_owner" GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "dwh-airflow_app", "dwh-airflow_developer";
ALTER DEFAULT PRIVILEGES FOR ROLE "dwh-airflow_owner" GRANT SELECT, UPDATE ON SEQUENCES TO "dwh-airflow_app", "dwh-airflow_developer";
ALTER DEFAULT PRIVILEGES FOR ROLE "dwh-airflow_owner" GRANT EXECUTE ON FUNCTIONS TO "dwh-airflow_app", "dwh-airflow_developer";
ALTER DEFAULT PRIVILEGES FOR ROLE "dwh-airflow_owner" GRANT USAGE ON TYPES TO "dwh-airflow_app", "dwh-airflow_developer";
ALTER DEFAULT PRIVILEGES FOR ROLE "dwh-airflow_owner" GRANT USAGE ON SCHEMAS TO "dwh-airflow_app", "dwh-airflow_developer";
ALTER DEFAULT PRIVILEGES FOR ROLE "dwh-airflow_owner" GRANT SELECT ON TABLES TO "dwh-airflow_readonly","dwh-airflow_dwh","dwh-airflow_report";
ALTER DEFAULT PRIVILEGES FOR ROLE "dwh-airflow_owner" GRANT USAGE ON TYPES TO "dwh-airflow_readonly","dwh-airflow_dwh","dwh-airflow_report";
ALTER DEFAULT PRIVILEGES FOR ROLE "dwh-airflow_owner" GRANT USAGE ON SCHEMAS TO "dwh-airflow_readonly","dwh-airflow_dwh","dwh-airflow_report";
ALTER DEFAULT PRIVILEGES FOR ROLE "dwh-airflow_owner" GRANT SELECT ON SEQUENCES TO "dwh-airflow_readonly","dwh-airflow_dwh","dwh-airflow_report";
CREATE ROLE "dwh-airflow_appuser" LOGIN IN ROLE "dwh-airflow_app";
ALTER ROLE "dwh-airflow_appuser" PASSWORD 'NxATcpUiuJ5PuAityYrG+';